compressionLevel: 0

enableGlobalCache: false

enableScripts: false

logFilters:
  ## DISABLED_BUILD_SCRIPTS
  - code: YN0004
    level: discard
  ## INCOMPATIBLE_OS - fsevents junk
  - code: YN0062
    level: discard

pnpEnableEsmLoader: false

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.5.1.cjs
